### ISSUE TITLE
ch.so.Laermemfindlichkeitsstufen Layer erfassen und materialized View erstellen

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-wms#10]
Daten hier: https://s3.eu-central-1.amazonaws.com/ch.so.arp.nutzungsplanung.oereb-dev/ch.so.arp.nutzungsplanung.oereb.xtf

Achtung: Layer muss bis aus weiteres wirklich `ch.so.Laermemfindlichkeitsstufen` heissen, also ohne "p".

**Comment by andreasneumann** [comment]
umgesetzt im commit https://github.com/sogis/oereb-wms/commit/531dabf326c0c412aeaa16b8b42aa6e5350a7993
