### ISSUE TITLE
ch.so.Waldabstandslinien Layer erfassen und materialized View erstellen

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-wms#11]
Dito https://github.com/sogis/oereb-wms/issues/10

Daten sind jetzt auch für dieses Thema im XTF.

**Comment by andreasneumann** [comment]
umgesetzt im commit https://github.com/sogis/oereb-wms/commit/531dabf326c0c412aeaa16b8b42aa6e5350a7993
