### ISSUE TITLE
Umgang t_basket beim Import via Db2Db

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-wms#12]
Aus der Diskussion mit Andi S.

- Basket-ID aus der ili2db-DB-Sequenz erstellen lassen
- Insert into ili2db-Metatabelle mittels INSERT WHERE NOT EXISTS, da nur beim allerersten Mal die Bastket-Id für z.B. die AV in die Metatabelle geschrieben werden muss. Der Datasetname where die NOT-EXIST Bedingung.
- Dann jeweils zum Löschen und neu Abfüllen der Tabellen die Basket-Id mit Subquery oder ähnlichem eruieren.

So ist garantiert, dass es keine Kollisionen gibt. Alles theoretisch, vielleicht geht es doch nicht.

**Comment by schmandr** [comment]
Man müsste hierzu mit einem SqlExecutor an die Basket ID herankommen und diese danach dem Db2Db Step als Parameter übergeben können. Aber das ist im Moment nicht möglich. Deshalb eine Lösung mit fixen Basket IDs für AV, PLZ etc. umgesetzt, wobei die IDs im negativen Bereich vergben werden (z.B. AV: -1).
