### ISSUE TITLE
Move from docker to travis

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-wms#14]
Damit wir CI/CD vereinheitlichen können, haben wir beschlossen nicht auf die Autobuilds von Docker zu setzen, sondern "nur" Travis.

**Comment by edigonzales** [comment]
@schmandr @andreasneumann Schaut euch das bitte zügig an.

**Comment by andreasneumann** [comment]
Good news:

Travis listet nun für meinen github account auch sogis repos. D.h. wir sollten das nun zügig fixen können.

![image](https://user-images.githubusercontent.com/884476/77061073-f48e2f00-69d9-11ea-8f49-761b08f82f60.png)

Geändert habe ich nichts. Lag wohl wirklich an einem Bug im Zusammenspiel von Github und Travis.

**Comment by andreasneumann** [comment]
Siehe https://github.com/sogis/oereb-wms/pull/26

**Comment by andreasneumann** [comment]
Ist nun umgesetzt.
