### ISSUE TITLE
docker-compose up --build fails

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-wms#16]
Sollte das lokal noch gehen?

**Comment by andreasneumann** [comment]
gefixt in https://github.com/sogis/oereb-wms/commit/921f86790131aaf82086283979ae6e69e94c3755 und https://github.com/sogis/oereb-db/commit/bb0f25205d2230e83a33c41bc04356b0c11342c0

Nutzungsplanungsdaten haben nun andere Quelle und Refresh mat views Issue behoben (owner-Probleme)
