### ISSUE TITLE
Kontrolle Bauliniensymbole

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-wms#17]
Es sieht so aus, ob hätten einige Liniensymbole einen dünnen durchgezogenen Strich:

https://geo-t.so.ch/wms/oereb?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphics&FORMAT=image/png&LAYER=ch.SO.Baulinien

Vielleicht täuscht es auch nur. Bitte überprüfen.

**Comment by andreasneumann** [comment]
Fixed with https://github.com/sogis/oereb-wms/commit/68e4b4a921ff7dd4efcf0bc079a9e511c9f73d73

Also changed line endings from square to flat, to make spaces between dashes a bit wider.
