### ISSUE TITLE
Die Dateien pg/pg_service_live.conf und pg/pg_service_stage.conf braucht es nicht

### ISSUE THREAD

**Issue by schmandr** [sogis/oereb-wms#18]
Ich habe die entsprechende Anpassung an _pg_service.conf_ in OpenShift gemacht, weil der WMS seither nicht mehr funktionierte (bzw. wieder zurück auf die letzte Version ging). Aber die Dateien _pg/pg_service_live.conf_ und _pg/pg_service_stage.conf_ braucht es eigentlich gar nicht, oder?

**Comment by andreasneumann** [comment]
Fixed in https://github.com/sogis/oereb-wms/commit/77594b9af72b80c7c6ef4c5d6ebb6e9344daf5a7
