### ISSUE TITLE
nutzungsplanung_sondernutzungsplaene_flaeche.qml anpassen.

### ISSUE THREAD

**Issue by Luescher** [sogis/oereb-wms#19]
Die Darstellung ist nicht optimal, da man mit dem s/w Plan für das Grundbuch fast nichts sieht. Die Idee (mit ARP besprochen)  ist, für den ÖREB-Kataster Bandierungen zu machen. Ich habe das ausprobiert. Karteneinheiten und  "Nur im folgende Massstab skalieren". Geht das mit dem Iconizer...

Nur habe ich da ein Problem ... es gibt so Lücken. Hast du eine Idee wie ma das in hübsch machen kann?

![Bandierung_problem](https://user-images.githubusercontent.com/3929984/67001759-b7480d00-f0da-11e9-819b-25fd0c5ebcd1.png)

**Comment by Luescher** [comment]
[nutzungsplanung_sondernutzungsplaene_flaeche_v2.zip](https://github.com/sogis/oereb-wms/files/3738762/nutzungsplanung_sondernutzungsplaene_flaeche_v2.zip)

**Comment by andreasneumann** [comment]
Hier ist es besser wenn man "Linie nur im Polygon zeichnen" verwendet:

![image](https://user-images.githubusercontent.com/884476/67007009-be751800-f0e6-11e9-900e-9aaf32a71b9a.png)

Dabei muss dann die Strichbreite verdoppelt werden, weil ja nur "innen" gezeichnet wird.

**Comment by andreasneumann** [comment]
siehe 
![image](https://user-images.githubusercontent.com/884476/67007252-41966e00-f0e7-11e9-8817-b476c1ab4188.png)

**Comment by andreasneumann** [comment]
Frage: ist die Bandierung des kommunalen Gestaltungsplans absichtlich breiter als der kantonale?

**Comment by andreasneumann** [comment]
Fixed in commit 77594b9
