### ISSUE TITLE
Empty views

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-wms#2]
Subthemen heissen neu anders: https://github.com/sogis/oereb-wms/blob/master/sql/oereb-wms-views.sql#L227 müsste `NutzungsplanungGrundnutzung` sein.

Ander wohl auch.

**Comment by andreasneumann** [comment]
Fixed in https://github.com/sogis/oereb-db/commit/f98f7771850672208363836e3d70fb5896dd2ba2

TODO: andere Themen soweit klar auch angepasst. Bundesthemen noch nicht alle.
