### ISSUE TITLE
Gerade eine Tabelle entdeckt, die im .qgs mit dem Schemanamen eingebunden ist

### ISSUE THREAD

**Issue by schmandr** [sogis/oereb-wms#20]
Wegen dem potentiellen Umstellen auf `stage` sollen aber ja keine Schemanamen im .qgs stehen.

https://github.com/sogis/oereb-wms/blob/e67fff4bf17d045a08e72a92a1fc41f605aa78ce/qgis/oereb.qgs#L179

**Comment by andreasneumann** [comment]
fixed with 5fad780cf9cf5c4a1b84759604ad5194ff22fe76
