### ISSUE TITLE
OnlineResoure müsste https... lauten

### ISSUE THREAD

**Issue by schmandr** [sogis/oereb-wms#21]
Wenn man https://geo-t.so.ch/wms/oereb?SERVICE=WMS&REQUEST=GetCapabilities aufruft, steht im GetCapabilities unter OnlineResource http://geo-t.so.ch/wms/oereb, also ohne http**s**. Dies hat damit zu tun, dass wir den Container "im http-Modus" betreiben. OpenShift erhält also den https-Request, leitet ihn aber als http-Request an den Container weiter. Das ist soweit OK.

Gibt es aber eine Möglichkeit, QGIS Server so zu konfigurieren, dass er in der Antwort auf GetCapabilities https in die URLs schreibt? Wir hatten dasselbe beim MapCache auch. Dort haben wir es so gelöst, dass wir die gesamte URL inkl. https in die Konfigurationsdateien geschrieben haben (was m.E. aber auch nicht ganz ideal ist): https://github.com/sogis/docker-mapcache/blob/4ad235f00e375d2495897e42525724b080968d19/mapcacheproduction.xml#L7

Dass nun http steht, macht zum Glück nicht allzu viele Probleme. Es ist vom Client abhängig, wie gut er damit umgehen kann.

**Comment by andreasneumann** [comment]
Man kann die URL hart codiert in der QGIS-Datei als Ressource reinschreiben - das hat jedoch gravierende Nachteile. Man kann dann, ohne die .qgs-Datei zu patchen den WMS nicht unter beliebigen URLs (geo-t, geo-i, geo, localhost) betreiben.

Eine Möglichkeit wäre, im Dockerfile, nach dem rein-kopieren der .qgs-Datei, mittels sed die .qgs-Datei zu patchen.

Machbar schon - elegant nicht. Was meinst Du, @schmandr ?

**Comment by andreasneumann** [comment]
Das Docker-File müsste dann seinen Kontext irgendwie kennen - läuft es unter der Test, Integrations oder Produktionsumgebung, oder unter localhost. Gibt es da eine Umgebungsvariable um das festzustellen in welcher Umgebung der Container läuft?

**Comment by andreasneumann** [comment]
@schmandr - was möchtest Du nun hier machen? Hart codiert https reinschreiben?

Woher weiss ich in welcher Umgebung oereb-wms läuft?

Ist das nicht mehr eine Deployment-Frage?

Ich sehe nicht wirklich, was ich hier tun kann?

**Comment by schmandr** [comment]
Ich könnte mir vorstellen, dass wir das einfach mit einer entsprechenden Konfiguration des Reverse Proxy (nginx) erreichen können (bzw. dass wir (ich) das von Anfang an hätten so machen sollen):

```
location /some/path/ {
    [...]
    proxy_set_header X-Forwarded-Proto https;
}
```
oder sogar

```
location /some/path/ {
    [...]
    proxy_set_header Forwarded proto=https;
}
```

Werde ich prüfen.

**Comment by schmandr** [comment]
Es scheint, dass Dinge wie `X-Forwarded-Proto https` oder auch `X-Forwarded-Host $http_host` den Apache (oder ist es QGIS Server?) diesbezüglich kalt lassen. (Was aber rein bezüglich Hostname funktionierte war `Host $http_host`; aber das müssen wir nicht separat setzen, weil wir das in der Nginx-Konfig global ohnehin schon machen.)

Eine andere Idee: Es könnte funktionieren, wenn man im Betrieb die Zeile
`ServerName 127.0.0.1`
in https://github.com/sogis/docker-qgis/blob/62f90e04e6a4462f75fcd0833cc6c72ef7fd42d2/qgis-server-base-3.4/qgis-server.conf#L1
ändert zu
`ServerName https://127.0.0.1`
Damit das geht, müsste man im Betrieb entweder das gesamte qgis-server.conf (mit dieser Anpassung) als ConfigMap in den Container mounten. Oder vielleicht liesse sich der ServerName über ein Include lösen, so dass man nur dies übersteuern müsste.

**Comment by schmandr** [comment]
Die Variante mit `ServerName https://127.0.0.1` hat fast, aber nicht ganz funktioniert:
Man muss dies in _qgis-server.conf_ innerhalb von `<VirtualHost *:80>` platzieren, nicht ausserhalb. Dann resultiert als _OnlineResource_ immerhin (aber eben doch nur): http://geo-t.so.ch:443/wms/oereb D.h. irgendwas wird hier von irgendeiner Software kapiert, aber nicht ganz so, wie wir es wollen.

Es braucht also weitere Tests. Ich würde vorläufig am Docker Image _oereb-wms_ nichts ändern.

**Comment by mbernasocchi** [comment]
@schmandr QGIS fcgi schaut sich den HTTPS parameter

in Nginx würde man so machen:

```
# Get 'host' from `$host` unless 'X-Forwarded-Host'
# is set by the reverse proxy.
# 'X-Forwarded-Host' may contain also the port,
# so it is removed from the variable
map $http_x_forwarded_host $qgis_host {
  "~(?[^:]+)" $h;
  default $host;
}
# Get 'PORT' from `$http_host`
map $http_host $port {
  "~*.*:(?
  .*)" $p;
  default $server_port;
}
# Get 'HTTPS' status from `$https` unless 'X-Forwarded-Proto'
# is set by the reverse proxy and contains 'https' scheme
map $http_x_forwarded_proto $qgis_ssl {
  "https" "on";
  default $https;
}
# Get 'PORT' from `$port` unless 'X-Forwarded-Port'
# is set by the reverse proxy
map $http_x_forwarded_port $qgis_port {
  "" $port;
  default $http_x_forwarded_port;
}
```

und in der location:
```
location /qgis/ {
  internal; # Used only by the OGC rewrite  
  root /var/www/data;
  fastcgi_pass localhost:9993;
  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  fastcgi_param QUERY_STRING $query_string;
  # build links in GetCapabilities based on
  # the hostname exposed by the reverse proxy
  fastcgi_param HTTPS $qgis_ssl;
  fastcgi_param SERVER_NAME $qgis_host;
  fastcgi_param SERVER_PORT $qgis_port;
  include fastcgi_params;
}

```
in apache müsste man so etwas änliches machen. weisst du gerade wie oder soll ich mich dokumentieren? Hab schon lange nicht mehr mit apache gearbeitet.

warscheindlich mit `FcgidInitialEnv HTTPS "on"` könnte man dies erzwingen

**Comment by schmandr** [comment]
Ich schliesse das Ticket, weil wir dieses Repo archivieren.

Mit Apache ist es wohl unlösbar.
