### ISSUE TITLE
Fix groundwater... symbol rules

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-wms#22]
Es können nicht die dreistelligen Artcodes aus der Nutzungsplanung verwendet werden, sondern es müssen `S1`, `S2`, `S3` und  `Areal` (gemäss MGDM, siehe edit-DB `afu_gewaesserschutz`) verwendet werden.

**Comment by andreasneumann** [comment]
Fixed with commit https://github.com/sogis/oereb-wms/commit/2d0bd32eb4ae8144e689bc3eefbf7dabc289b5f1
