### ISSUE TITLE
WMS-Layer Statische Waldgrenzen hinzufügen

### ISSUE THREAD

**Issue by schmandr** [sogis/oereb-wms#23]
Wenn ich es richtig sehe, fehlt im Moment der WMS-Layer "Statische Waldgrenzen" noch.

**Comment by andreasneumann** [comment]
Hallo @schmandr - wie dringend ist das? Reicht es, wenn ich das am 23.1. mache oder braucht ihr das schneller?

**Comment by schmandr** [comment]
Ich weiss es nicht, aber @Luescher kann das sagen.

**Comment by Luescher** [comment]
23. Januar reicht. Ende Januar möchte ich live gehen mit den Waldgrenzen

**Comment by andreasneumann** [comment]
Fixed in https://github.com/sogis/oereb-wms/commit/452e3bde09c1b3f0204a509355b616c549388402
