### ISSUE TITLE
Darstellung Statische Waldgrenzen 

### ISSUE THREAD

**Issue by Luescher** [sogis/oereb-wms#24]
Die dicke der Linie soll gleich sein wie bei der Waldabstandslinie

**Comment by andreasneumann** [comment]
Fixed in https://github.com/sogis/oereb-wms/commit/b793f3cc29b267cf2bf60a1d448a0f37d85e1fec

@Luescher @schmandr in der Testumgebung wird ja der oereb-wms automatisch neu ausgerollt. In der Integration und Produktion nicht. Soll @schmandr das dort neu ausrollen?

**Comment by schmandr** [comment]
In der Integrationsumgebung habe ich nun Version b793f3c (dieselbe wie in der Testumgebung) ausgerollt, weil wir das gestern auf dem Heimweg noch so besprochen haben.

Bezüglich Produktionsumgebung warte ich aber auf einen entsprechenden Auftrag.

**Comment by schmandr** [comment]
Ich habe nach Rücksprache mit @Luescher soeben auch die Produktionsumgebung auf b793f3c aktualisiert.
