### ISSUE TITLE
Grundwasserschutzzonen und -areal kommen mit der neusten Version nicht mehr

### ISSUE THREAD

**Issue by Luescher** [sogis/oereb-wms#25]
WMS zeigt keine Objekte ... resp. leer

**Comment by andreasneumann** [comment]
@Luescher - hast Du mehr Hinweise?

Scheint bei mir tadellos zu gehen - siehe Screenshot aus dem QGIS:
![image](https://user-images.githubusercontent.com/884476/76882560-2046d300-687b-11ea-9832-d19593e88836.png)


Oder ist was bei den Layernamen falsch?

**Comment by Luescher** [comment]
Screenshot aus der Testumgebung. Der WMS wird nicht dargestellt im Kartenfenster 
![gws](https://user-images.githubusercontent.com/3929984/77041925-10360d00-69bb-11ea-80e1-b2852f126d35.jpg)

**Comment by Luescher** [comment]
In ÖREB-DB verweiswms 
https://geo.so.ch/wms/oereb?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.SO.Grundwasserschutzzonen&STYLES=&SRS=EPSG%3A2056&CRS=EPSG%3A2056&DPI=96&WIDTH=1200&HEIGHT=1146&BBOX=2591250%2C1211350%2C2646050%2C1263700

**Comment by andreasneumann** [comment]
In der scharfen Version geht der WMS, in Test und Integration nicht.

Ich bin am analysieren woran das Problem liegen könnte. Ich schaue mir gerade die Daten in der DB an, ob die in Test und Integration in Ordnung sind.

Ev. brauche ich die Hilfe von @schmandr oder @pfeimich um zu sehen ob wirklich überall die gleiche Version des ÖREB-WMS läuft?

**Comment by andreasneumann** [comment]
Die Daten (PG) sind in allen 3 Versionen (test, integration und produktion) in Ordnung.

**Comment by schmandr** [comment]
> In der scharfen Version geht der WMS, in Test und Integration nicht.

In der Produktionsumgebung funktioniert es deshalb, weil hier noch eine ältere Version des WMS läuft. Bzw. es ist genau genommen so, dass ich am 27.2.2020 in Absprache mit @Luescher in der Produktionsumgebung ebenfalls auf die neuste Version des Images aktualisiert habe; dann hat @Luescher festgestellt, dass die Grundwasserschutzzonen nicht mehr funktionieren, worauf ich die Sache wieder auf die Version a1f4432 zurückgestellt habe.

**Comment by andreasneumann** [comment]
Ok - Problem gefunden:

Der commit https://github.com/sogis/oereb-wms/commit/2d0bd32eb4ae8144e689bc3eefbf7dabc289b5f1 hatte zwar die .qml-Dateien und die Datei oereb-symbols.qgs korrigiert, aber aus irgendeinem Grund (wohl Fehler von mir) nicht die Datei oereb.qgs

D.h. die Symbologie im oereb.qgs hat sich immer noch auf den 3-stelligen Zahlencode statt auf den Text-Wert abgestützt.

Ich mache einen Fix.

**Comment by andreasneumann** [comment]
Siehe commit https://github.com/sogis/oereb-wms/commit/2806ff07832d5e3b0ffd99e14102e4f8bcfe1d19 - der sollte das Problem beheben.

Ich schliesse das Ticket, wenn der WMS in der Testumgebung funktioniert.

**Comment by andreasneumann** [comment]
@Luescher und @schmandr 

https://geo-t.so.ch/wms/oereb?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.SO.Grundwasserschutzzonen&STYLES=&SRS=EPSG%3A2056&CRS=EPSG%3A2056&DPI=96&WIDTH=1200&HEIGHT=1146&BBOX=2591250%2C1211350%2C2646050%2C1263700 funktioniert nun neu.

Aber unter https://geo-t.so.ch/map/ funktioniert es noch nicht. Muss da noch was neu gestartet werden?

**Comment by schmandr** [comment]
Ich glaube nicht, dass etwas neu gestartet werden muss. Wo zum Beispiel geht es denn in der Produktionsumgebung?

**Comment by andreasneumann** [comment]
Wenn Du im Web-GIS nach "687 Wisen" suchst. Dort hat es eine Grundwasserschutzzone.

In der Produktion geht es (mit altem oereb-wms), in der Testumgebung geht es (noch) nicht, obwohl https://geo-t.so.ch/wms/oereb?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.SO.Grundwasserschutzzonen&STYLES=&SRS=EPSG%3A2056&CRS=EPSG%3A2056&DPI=96&WIDTH=1200&HEIGHT=1146&BBOX=2591250%2C1211350%2C2646050%2C1263700 nun funktioniert. Das funktionierte vor meinem symbology-fix auch nicht.

Ich fürchte ich kann im Moment nicht mehr rausfinden.

**Comment by schmandr** [comment]
Danke.

Ah, schon herausgefunden: Der Web GIS Client Test zeigt auf den OEREB-WMS Integration. Muss ich mit Michael anschauen. Dies könnte bei dem Zurücksetzen der Test-DB auf den Stand der Produktions-DB (bzw. hier eben wohl der Integrations-DB) passiert sein...

**Comment by schmandr** [comment]
So, nun zeigt die Geschichte auf den OEREB-WMS der Testumgebung. Problem war: Mit dem Reset der oereb-DB Test auf den Stand der oereb-DB Integration stehen jetzt in der Test-DB die Verweise auf die WMS-URLs der Integrationsumgebung. Ich habe dies für diesen Datensatz manuell geändert. Theoretisch würde man besser die OEREB-GRETL-Jobs nochmal ausführen, aber genau dieser Job schlägt fehl, weil die Daten nicht valide sind...


Mit dem Rollout in der Integrations- und Produktionsumgebung warten wir noch zu, bis die Abnahme abgeschlossen ist. Aus meiner Sicht kann das Ticket aber trotzdem geschlossen werden.

**Comment by andreasneumann** [comment]
Funktioniert nun in Testumgebung
