### ISSUE TITLE
Lärmempfindlichkeitsstufen - ESII hat falsche Farbe

### ISSUE THREAD

**Issue by Luescher** [sogis/oereb-wms#27]
Mangel von der Systemabnahme durch den Bund:
"Die Farbgebung der Legende für ES II ist falsch. Sie hat den gleichen Farbton wie ES II aufgestuft, nur ohne Punkte (s. vollständige Legende); Winznau 298"

Siehe Seite 42
[](https://www.are.admin.ch/dam/are/de/dokumente/raumplanung/minimale_geodatenmodellebereichnutzungsplanung-modelldokumentati.pdf.download.pdf/minimale_geodatenmodellebereichnutzungsplanung-modelldokumentati.pdf )

**Comment by andreasneumann** [comment]
@Luescher - wenn Du mir verrätst wo das von Dir zitierte Dokument liegt (Seite 42) mache ich das gerne so rasch wie möglich, vorausgesetzt die Werte sind dort klar ersichtlich.

**Comment by Luescher** [comment]
https://www.are.admin.ch/dam/are/de/dokumente/raumplanung/minimale_geodatenmodellebereichnutzungsplanung-modelldokumentati.pdf.download.pdf/minimale_geodatenmodellebereichnutzungsplanung-modelldokumentati.pdf

**Comment by Luescher** [comment]
Link hat es mir komischerweise entfernt....

**Comment by andreasneumann** [comment]
Fixed in https://github.com/sogis/oereb-wms/commit/6699ce4a7a6d21780fca0a3307059b274b2923a1
