### ISSUE TITLE
Walgrenzen müssen angepasst werden

### ISSUE THREAD

**Issue by Luescher** [sogis/oereb-wms#29]
Siehe https://github.com/sogis/oereb-gretljobs/issues/114

Legendentest zwingend:
-in Bauzonen 
-ausserhalb Bauzonen

Darstellung:
- "in Bauzonen"  so wie jetzt hellgrün gestrichelt. Breite von 0.7 auf 1.0 setzten. War generell zu dünn
- "ausserhalb Bauzonen" gleiches hellgrün, Linie durchgezogen 1.0 Dicke

**Comment by Luescher** [comment]
auf der Testumgebung ist die Aussage und der artcode angepasst.

**Comment by andreasneumann** [comment]
hm - da ist nun ein Widerspruch:

Du schreibst hier im Ticket "in Bauzonen" soll strichliert sein, und "ausserhalb Bauzonen" durchgezogen, aber in https://github.com/sogis/oereb-gretljobs/issues/114 steht es genau umgekehrt.

Welche Variante gilt? Und die Linien bleiben grün, oder?

**Comment by andreasneumann** [comment]
siehe branch https://github.com/sogis/oereb-wms/tree/waldgrenzen_symbologie

Ich werde das in master mergen und in Test-Umgebung ausprobieren. Falls noch Probleme auftreten rollen wir das zurück.

**Comment by andreasneumann** [comment]
In der Testumgebung ausgerollt. Gretljob nochmals ausgeführt, damit Dummy-Symbol durch richtiges ersetzt wird.

**Comment by Luescher** [comment]
i.O.
