### ISSUE TITLE
Hintergrundkarte - Auswirkungen?

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-wms#3]
Hat Hintergrundkarte garantiert keine Auswirkungen auf die Server-Performanz? Auch wenn sie "excluded" ist?

**Comment by andreasneumann** [comment]
Ich glaube nicht, dass ein "excluded layer" einen negativen Impact auf die Performance hat, aber wir können den Layer trotzdem rausnehmen - er ist ja nicht wirklich nötig. Ich mache einen Commit dafür.

**Comment by andreasneumann** [comment]
Hintergrund-Layer entfernt. Im geopackage oereb-symbols.qgs bleibt der Hintergrundlayer vorerst drinnen.
