### ISSUE TITLE
Darstellung bei Grundwasserschutzzonen muss erweitert werden mit Sh und Sm

### ISSUE THREAD

**Issue by Luescher** [sogis/oereb-wms#31]
Siehe https://www.bafu.admin.ch/dam/bafu/de/dokumente/wasser/geodatenmodell/planerischer_gewaesserschutz.1.zip.download.zip/planerischer_gewaesserschutz.zip
![sh_sm](https://user-images.githubusercontent.com/3929984/104331466-63032700-54ef-11eb-826e-54e70d3988a3.jpg)

Siehe auch https://github.com/sogis/oereb-gretljobs/issues/146

**Comment by andreasneumann** [comment]
artcode = "Sh" und "Sm"?

Die Symbologie-Regel verwendet die Spalte "artcode".

CC @Luescher @barpasen

**Comment by Luescher** [comment]
ja

**Comment by Luescher** [comment]
beim Datenumbau muss hier nichts angepasst werden.  Im gwszone.typ steht Sh und Sm

 gwszone.typ AS artcode

**Comment by barpasen** [comment]
Pull Request gemacht

**Comment by andreasneumann** [comment]
Siehe https://github.com/sogis/oereb-wms/commit/d7ff54e6c633aed4260f4745998324b745801554

**Comment by Luescher** [comment]
zur Vollständigkeit braucht es noch S3Zu und S_kantonaleArt (=artcode)
![S3Zu](https://user-images.githubusercontent.com/3929984/104554664-cf3f7100-563c-11eb-9144-77b8105934bd.jpg)


Das wären alle Typen die es gemäss MGDM gibt:
S1,
S2,
S3,
S3Zu,
S_kantonaleArt,
Sh,
Sm

**Comment by andreasneumann** [comment]
umgesetzt in https://github.com/sogis/oereb-wms/commit/883f4b9dd542e4454ff785c89452dacaa443084b
