### ISSUE TITLE
artcode=naturschutzgebiete  "e" fehlt

### ISSUE THREAD

**Issue by Luescher** [sogis/oereb-wms#32]
qml muss angepasst werden.

ist: artcode=naturschutzgebiet 
soll: artcode=naturschutzgebiete

Ist wahrscheinlich mein "Kommunikations-Fehler"

**Comment by andreasneumann** [comment]
umgesetzt mit https://github.com/sogis/oereb-wms/commit/7b3584bd21efeb2f8543b1b7e6b5932218311ba9

Muss in Integration und natürlich auch in Produktion von Hand ausgerollt werden.
