### ISSUE TITLE
Vollständige Legende Text nicht identisch zur ÖREB-Aussage

### ISSUE THREAD

**Issue by Luescher** [sogis/oereb-wms#33]
Bei der Vollständige Legende kommen die "e" nicht
![vollständige_Legende](https://user-images.githubusercontent.com/3929984/109479155-655b1980-7a7a-11eb-9663-db930c97066e.jpg)

Anpassung QML weiteres_thema_einzelschutz_punkt.qml:
label="Geotop**e**"

Anpassung QML weiteres_thema_einzelschutz_flaeche.qml:
label="Geotop**e**"
label="Naturschutzgebiet**e**"

Bitte Änderung gleich ausrollen lassen auf Produktionsumgebung.

**Comment by andreasneumann** [comment]
siehe commit https://github.com/sogis/oereb-wms/commit/613a899004e198d20efb2e77dd9c9e701991e2bf

Ticket wird geschlossen wenn es ausgerollt ist.

**Comment by andreasneumann** [comment]
@schmandr - kannst Du das bitte in Integration und Produktion ausrollen? Merci!

Nach dem Ausrollen bitte Ticket schliessen!

**Comment by schmandr** [comment]
Ist ausgerollt (Tag [31](https://hub.docker.com/layers/sogis/oereb-wms/31/images/sha256-8316e3bb47189fe9093e8ac79e91040ad5802e451c08eaa76569c7e009a84df6?context=explore))
