### ISSUE TITLE
dummy-daten.gpkg wird (zumindest in OpenShift) mit Schreibzugriff geöffnet

### ISSUE THREAD

**Issue by schmandr** [sogis/oereb-wms#4]
Beim Aufruf von https://geo-t.so.ch/wms/oereb-symbols?SERVICE=WMS&REQUEST=GetStyles&LAYERS=ch.so.Nutzungsplanung.NutzungsplanungGrundnutzung wird im Apache Error Log folgendes gemeldet:

```
Warning 4: Failed to open /data/dummy-daten.gpkg, Permission denied.
ERROR 1: attempt to write a readonly database: this file is a WAL-enabled database. It cannot be opened because it is presumably read-only or in a read-only directory.

```
Wenn ich testweise
```
chown :www-data /data
chmod g+w /data
chown :www-data /data/dummy-daten.gpkg
chmod g+w /data/dummy-daten.gpkg
```
mache, funktioniert der Aufruf, und es werden die Dateien `/data/dummy-daten.gpkg-shm` und `/data/dummy-daten.gpkg-wal` angelegt (gehören dann dem User www-data).

Ich hoffe, es gibt eine andere Lösung als diese hier.
* Kann man z.B. QGIS (GDAL) mitteilen, dass es das GeoPackage nur lesend öffnen soll?
* Muss ich in OpenShift irgendwas besonders konfigurieren?

**Comment by edigonzales** [comment]
- Warum funktioniert lokal ein lokaler Build? 
- Hat mal funktioniert.

Schaus mir an.

**Comment by edigonzales** [comment]
Mmmmh, schaffe es nicht mehr, dass es mit einem lokalen Build funktioniert.

**Comment by schmandr** [comment]
Einen Versuch wert: Umgebungsvariable `OGR_SQLITE_JOURNAL=DELETE` setzen (Quelle: https://gis.stackexchange.com/a/224200). Diese muss man im Fall von QGIS Server wohl ebenfalls in _/etc/apache2/mods-enabled/env.conf_ definieren (Beispiel siehe letzte Zeile im Dockerfile).

**Comment by andreasneumann** [comment]
Das Problem hatten wir doch auch auf den Rechnern von @schmandr und @barpasen 
- man musste docker-compose aktualisieren dass es funktionierte.

Anscheinend haben ältere Versionen von docker-compose das gemountete volume nicht richtig als "read-only" ausgewiesen.

Das update von docker-compose hat das Problem behoben.

**Comment by edigonzales** [comment]
Nicht sicher, ob es das gleiche Problem ist:
- Ich habe nicht `docker-compose` verwendet, sondern `docker run`
- Es wird nichts gemounted.
- docker-compose ist aktuell

Was funktionierte:
- `chown -R www-data:www-data /data` im Dockerfile
- Im Base Image das `/data`-Verzeichnis nicht als Volumen exposen, weil sonst obiger Befehl nichts bewirkt.

**Comment by edigonzales** [comment]
Da v.a. wegen "root" das Base Image neu gemacht werden sollte, Ticke als Reminder offen lassen.

Falls es für das Problem hier bessere Lösungen gibt, kann man die selbstverständlich machen.

**Comment by andreasneumann** [comment]
Sollen wir die Dummy-Daten auch in die PG reinnehmen statt Geopackage?

**Comment by edigonzales** [comment]
Nein, lieber nicht. So ist das Image auch ohne PostgreSQL lauffähig. Ist noch ganz praktisch so.

**Comment by schmandr** [comment]
Der Fehler tritt nicht mehr auf. Wahrscheinlich seit der Änderung 433182b

Und der Ticket-Historie entnehme ich:

> Da v.a. wegen "root" das Base Image neu gemacht werden sollte, Ticke als Reminder offen lassen.

Dann können wir das Ticket entweder schliessen, oder wir lassen es eben als Reminder offen. Aber machen müssen wir m.E. im Moment nichts.
(Der Reminder ist wohl so gemeint: "Image neu erstellen, so dass es ohne root-Rechte läuft".)

**Comment by schmandr** [comment]
Ich schliesse das Ticket, weil wir dieses Repo archivieren.
