### ISSUE TITLE
WFS

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-wms#5]
Was machen wir mit einem möglichen WFS-Output?

**Comment by andreasneumann** [comment]
Wollt ihr WFS oder soll ich alle Layer für WFS deaktivieren?

Oder braucht es WFS sogar?

**Comment by edigonzales** [comment]
Ich bin für alle deaktivieren.

**Comment by andreasneumann** [comment]
WFS/WMTS deaktiviert: https://github.com/sogis/oereb-wms/commit/89f03a4a9bb3098fbf209cb4cfb05108a105b4a7
