### ISSUE TITLE
Fehlende Dokumente in den materialisierten Views

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-wms#6]
In der Definition der materialisierten View werden die direkt verlinkten Dokumente (also zwischen Eigentumsbeschränkung und Dokument) gar nicht berücksichtigt, sondern nur Dokumente, die in der Klasse `vorschriften_hinweisweiteredokumente` referenziert werden.

Siehe Anhang für Grundnutzung. Muss sehr gut getestet werden. 

[fix-view.sql.zip](https://github.com/sogis/oereb-wms/files/3511087/fix-view.sql.zip)

**Comment by andreasneumann** [comment]
Ich habe mal die Views gemäss dem vorgeschlagenen Fix erneuert: https://github.com/sogis/oereb-db/commit/9d79e187a3dd4f35d0f798b7c5ecfb5267bd35ec

Wie können wir die Ergebnisse verifizieren? Gibt es einen oder mehrere Testcases bei denen wir sicher sind welche Dokumente dranhängen müssen?

**Comment by edigonzales** [comment]
Meine Erleuchtung vom Wochenende: Es braucht so etwas wie Unit-Tests:

Du brauchst ein paar minimalste, handgeschriebene Transferstruktur-XTF, wo die sicher bist, wie das JSON am Schluss in der DB aussehen soll. Z.B.:

- Eine Eigentumsbeschränkung mit einer Rechtsvorschrift.
- Eine Eigentumsbeschränkung mit zwei Rechtsvorschriften.
- Eine Eigentumbeschränkung mit einer Rechtsvorschrift, die wiederum auf ein Dokument verweist (, das wiederum auf ein Dokument zeigt).
- Zwei Rechtsvorschriften. Eine Rechtsvorschrift ist direkt mit einem Dokument verlinkt. Die andere zuerst mit einem anderen Dokument, dieses wiederum auf das Dokument, das von der ersten direkt verlinkt ist (war glaubs mal ein Fehler im Umbau).

Peter braucht was ähnliches, nur halt mit dem kantonalen Modell als Input.
