### ISSUE TITLE
WMS für Stage-Schema

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-wms#7]
Es braucht ja für den Validierungsschritt die WMS auch aus den Daten des Stage-Schemas. Wie machen wir das? Gibt es andere Varianten als ein zweites QGS-File?

**Comment by andreasneumann** [comment]
Vielleicht können wir dafür ein alternatives pg_service.conf file machen?

Geht das @schmandr ?

Auch bei den Datenimport-Prozessen (z.b. Import AV) müssen wir noch was anpassen für den Import ins Staging Schema.

**Comment by edigonzales** [comment]
Beim Datenimport (AV, PLZ-Ortschaft, Grundbuchkreise) könnte man auch das Schema über einen Parameter im SQL-File steuern. Im Gegensatz zu den eher komplexen Umbauten im engeren ÖREB-Kontext, könnte man hier das "Risiko" der leicht verminderten Transparenz eingehen.

**Comment by schmandr** [comment]
Alternatives pg_service.conf könnte funktionieren... Im .qgs steht ja z.B.
`<datasource>service='oereb' key='"t_id"' srid=2056 type=LineString checkPrimaryKeyUnicity='0' table="live"."vw_oerebwms_nutzungsplanung_baulinien_linie" (geom) sql=</datasource>`

D.h. der Layer greift immer aufs Schema _live_ zu, egal, was in pg_service.conf steht. Es darf hier also nur `table="vw_oerebwms_nutzungsplanung_baulinien_linie"` heissen. Dann könnten wir versuchen, in pg_service.conf in etwa die Zeile
`options=-c search_path=public,live`
anzuhängen und schauen, ob das so funktioniert.

Irendwie wäre mir allerdings ein zweiter Service im gleichen Service File etwas lieber statt ein zweites Service File. Wäre das auch ein Szenario?

**Comment by andreasneumann** [comment]
Nach Diskussion im ÖREB-Sprint vom 10.10. hat sich herausgestellt, dass dies nicht mehr nötig ist, da die Staging-Daten über das Web-GIS kontrolliert werden können.
