### ISSUE TITLE
Renderingorder "weitere Schutzzonen ausserhalb Bauzone"

### ISSUE THREAD

**Issue by edigonzales** [sogis/oereb-wms#8]
Siehe Screenshot. Sollte das gestrichelte nicht immer über der Füllung liegen? Wenn es ein Nachbarpolygon hat, kann es überdeckt werden.
![Screenshot 2019-08-17 at 16 09 53](https://user-images.githubusercontent.com/2767800/63212781-ac3c2500-c109-11e9-8e95-d5ba7d1438ed.png)

**Comment by andreasneumann** [comment]
An der Symbologie hab ich gegenüber den bestehenden qmls der Nutzungsplanung bisher gar nichts geändert. Gemäss Andrea war die bisherige Symbologie in Ordnung. Aber es stimmt, die Strichlierung sollte immer über der Füllung liegen. Es sollte auch in den Nutzungsplanung des bestehenden Web-GIS behoben werden ...

Im Commit https://github.com/sogis/oereb-wms/commit/1f662880792470066bc6371bcb22114a344490f3 sind nun die symbol levels aktiviert und die strichlierte Linie wird in separatem rendering-Durchgang gezeichnet.
